# Based on the "trust" template v0.1.2
# https://github.com/japaric/trust/tree/v0.1.2

environment:
  global:
    RUST_VERSION: stable
    CRATE_NAME: vdot

  matrix:
    # MSVC
    - TARGET: x86_64-pc-windows-msvc

install:
  - ps: >-
      If ($Env:TARGET -eq 'x86_64-pc-windows-gnu') {
        $Env:PATH += ';C:\msys64\mingw64\bin'
      } ElseIf ($Env:TARGET -eq 'i686-pc-windows-gnu') {
        $Env:PATH += ';C:\msys64\mingw32\bin'
      }
  - curl -sSf -o rustup-init.exe https://win.rustup.rs/
  - rustup-init.exe -y --default-host %TARGET% --default-toolchain %RUST_VERSION%
  - set PATH=%PATH%;C:\Users\appveyor\.cargo\bin
  - rustc -Vv
  - cargo -V

test_script:
  - cargo build --target %TARGET%
  - cargo test --target %TARGET%

before_deploy:
  - sed -i "s/\"0.0.0\"/\"%APPVEYOR_REPO_TAG_NAME:~1%\"/" Cargo.toml
  - cargo rustc --target %TARGET% --release --bin vdot -- -C lto
  - ps: ci\before_deploy.ps1

deploy:
  artifact: /.*\.zip/
  auth_token:
    secure: CsdL/CTbBWyPqXHKCABx6DpWFUE/4BVoXxGkT1ArTd6UtJCzh+plitVSmGeq0yQq
  description: ''
  on:
    RUST_VERSION: stable
    appveyor_repo_tag: true
  provider: GitHub

cache:
  - C:\Users\appveyor\.cargo\registry
  - target

notifications:
  - provider: Email
    on_build_success: false
    on_build_failure: false

# Building is done in the test phase, so we disable Appveyor's build phase.
build: false