[package]
name = "vdot"
description = "Create your .env files using Vault."
version = "0.0.0"
authors = ["Samuel Parkinson <sam.james.parkinson@gmail.com>"]
edition = "2018"
repository = "https://github.com/sjparknson/vdot"
readme = "README.md"
license = "MIT"
categories = ["command-line-utilities", "config"]
keywords = ["cli"]

[badges]
travis-ci = { repository = "sjparkinson/vdot", branch = "master" }

[dependencies]
clap = { version = "2.32.0", features = ["wrap_help"] }
failure = "0.1.5"
fern = { version = "0.5.2", features = ["colored"] }
log = "0.4.6"
structopt = "0.2.15"
url = "1.7.2"

[profile.release]
lto = true
