[package]
name = "vdot"
description = "Create your .env files and start processes using Vault."
version = "0.0.0"
authors = ["Samuel Parkinson <sam.james.parkinson@gmail.com>"]
edition = "2018"
repository = "https://github.com/sjparkinson/vdot"
readme = "README.md"
license = "MIT"
categories = ["command-line-utilities", "config"]
keywords = ["cli", "env", "dotenv", "config"]

[badges]
travis-ci = { repository = "sjparkinson/vdot", branch = "master" }

[dependencies]
failure = "0.1.6"
fern = { version = "0.5.9", features = ["colored"] }
log = "0.4.8"
reqwest = { version = "0.9.22" }
serde = { version = "1.0.102", features = ["derive"] }
serde_json = "1.0.41"
structopt = "0.3.3"

[profile.release]
opt-level = 's'
lto = 'fat'
panic = 'abort'
