name: Build

on:
  push:
    branches: '**'

jobs:
  build:
    strategy:
      matrix:
        item:
          - os: macOS-latest
            target: x86_64-apple-darwin
          - os: ubuntu-latest
            target: x86_64-unknown-linux-musl
          - os: windows-latest
            target: x86_64-pc-windows-msvc

    runs-on: ${{ matrix.item.os }}

    steps:
      - uses: actions/checkout@v1

      - name: Cache cargo build
        uses: actions/cache@v1
        with:
          path: target
          key: ${{ runner.os }}-cargo-build-target-${{ hashFiles('**/Cargo.lock') }}

      - name: Install apt packages
        if: matrix.item.os == 'ubuntu-latest'
        shell: bash
        run: sudo apt install musl-tools

      - name: Install rust stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: ${{ matrix.item.target }}
          profile: minimal

      - name: Run cargo check
        uses: actions-rs/cargo@v1
        with:
          command: check

      - name: Run cargo test
        uses: actions-rs/cargo@v1
        with:
          command: test

      - name: Run cargo build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --target "${{ matrix.item.target }}"

      - name: Upload macOS and linux artifacts
        if: matrix.item.os == 'ubuntu-latest' || matrix.item.os == 'macOS-latest'
        uses: actions/upload-artifact@master
        with:
          name: vdot-${{ matrix.item.target }}
          path: target/${{ matrix.item.target }}/debug/vdot

      - name: Upload Windows artifacts
        if: matrix.item.os == 'windows-latest'
        uses: actions/upload-artifact@master
        with:
          name: vdot-${{ matrix.item.target }}
          path: target/${{ matrix.item.target }}/debug/vdot.exe
